Remove unused performance test
Performance tests have been removed in newer versions of Rails[1].

The presence of this unused test resulted in errors when upgrading to Rails 4.2:

    LoadError: cannot load such file -- rails/performance_test_help

[1]: https://github.com/rails/rails-perftest#installation